// @ts-check
// Auto-generated sidebar: drop a Markdown file into docs/ (with an optional
// `sidebar_position:` in frontmatter) and it appears in the guide automatically.
// Group pages by putting them in a folder with a `_category_.json`.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
